#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Gary Bissett <gary.bissett@gmail.com>
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

"""Turns the design pack in ``icons/pack`` into icons Qt can actually draw.

The pack is what the design produced and is kept as delivered. It cannot be
used directly, for two reasons found by rendering it:

*Qt ignores ``clip-path``.* QtSvg 6.10 draws a clipped shape unclipped -- the
app icon comes out as two rectangles rather than a plectrum, and the fret dots
of an instrument badge run off the edge of its disc. ``mask`` it does support,
and a clip is a mask of one white shape, so every ``clipPath`` here becomes one.

*The wordmark is text in a font.* The pack sets the ``f`` in Source Serif 4,
which renders as whatever serif happens to be installed, or as nothing. The
glyph is taken from the vendored font once, here, and written into the file as
a path -- so the icon is the same drawing on a machine with no fonts at all.

Run it after changing the pack. It writes only into ``icons/``, never into
``icons/pack``. ``instrument-note.svg`` is not written here: the pack has a
badge for a guitar, a bass, a kit and a keyboard, and nothing for the saxophone
a score is entitled to contain, so that one is drawn by hand beside it.
"""

import re
import sys
import xml.etree.ElementTree as ElementTree
from pathlib import Path

from fontTools.misc.transform import Transform
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

SVG = "http://www.w3.org/2000/svg"
HERE = Path(__file__).resolve().parent
PACK = HERE / "pack" / "svg"
FONTS = HERE.parent / "fonts"

APP = "io.github.sonicp3l1c4n.fretwork"

# What a KDE icon theme is asked for. The pack ships 16 and 256 as well; these
# are the sizes hicolor is installed into, and every one is drawn from the same
# corrected SVG so they cannot disagree about the shape.
PNG_SIZES = [24, 32, 48, 64, 96, 128]

# Without an em dash this would say "pack -- edit", and two hyphens inside an
# XML comment are illegal. Qt is the parser that says so, with an error naming
# neither comments nor hyphens; every other reader accepted the file.
NOTICE = (
    "Generated by icons/from-pack.py from icons/pack \u2014 edit the pack, not this."
)


def font_for(style: str) -> TTFont:
    return TTFont(FONTS / f"SourceSerif4-{style}.ttf")


def glyph_path(font: TTFont, character: str, size: float, x: float, y: float,
               anchor: str) -> str:
    """One character as a path, placed where the ``<text>`` element put it."""
    glyph_set = font.getGlyphSet()
    name = font.getBestCmap()[ord(character)]
    advance = font["hmtx"][name][0]
    scale = size / font["head"].unitsPerEm
    if anchor == "middle":
        x -= advance * scale / 2
    elif anchor == "end":
        x -= advance * scale

    pen = SVGPathPen(glyph_set, ntos=lambda value: format(round(value, 2), "g"))
    glyph_set[name].draw(TransformPen(pen, Transform(scale, 0, 0, -scale, x, y)))
    return pen.getCommands()


def text_to_path(element: ElementTree.Element) -> ElementTree.Element:
    """A ``<text>`` element as the ``<path>`` it draws."""
    italic = element.get("font-style") == "italic"
    weight = element.get("font-weight", "400")
    style = "Semibold" if int(weight) >= 600 else "Regular"
    if italic:
        style = "SemiboldIt" if style == "Semibold" else "It"

    commands = []
    x = float(element.get("x", 0))
    for character in element.text or "":
        font = font_for(style)
        commands.append(glyph_path(font, character, float(element.get("font-size", 16)),
                                   x, float(element.get("y", 0)),
                                   element.get("text-anchor", "start")))
        # Only the single-glyph wordmarks here, but a word has to advance or
        # "Fretwork" would be eight letters in the same place.
        glyph_set = font.getGlyphSet()
        name = font.getBestCmap()[ord(character)]
        x += (font["hmtx"][name][0]
              * float(element.get("font-size", 16)) / font["head"].unitsPerEm)

    path = ElementTree.Element(f"{{{SVG}}}path")
    path.set("d", " ".join(commands))
    for carry in ("fill", "mask", "clip-path", "opacity"):
        if element.get(carry):
            path.set(carry, element.get(carry))
    return path


def correct(source: Path) -> str:
    """The pack's drawing, with clips turned into masks and text into paths."""
    ElementTree.register_namespace("", SVG)
    tree = ElementTree.parse(source)
    root = tree.getroot()

    # A clip is a mask whose shape is white and whose surroundings are the
    # black a mask starts as, so this is a rename and a fill.
    for parent in root.iter():
        for index, child in enumerate(list(parent)):
            if child.tag == f"{{{SVG}}}clipPath":
                mask = ElementTree.Element(f"{{{SVG}}}mask")
                mask.set("id", child.get("id"))
                for shape in child:
                    shape.set("fill", "#fff")
                    mask.append(shape)
                parent[index] = mask
    for element in root.iter():
        if element.get("clip-path"):
            element.set("mask", element.attrib.pop("clip-path"))

    for parent in root.iter():
        for index, child in enumerate(list(parent)):
            if child.tag == f"{{{SVG}}}text":
                parent[index] = text_to_path(child)

    # A group with nothing in it and a mask on it. The pack's drum badge has
    # one, left behind by a knockout that needed no overdrawn detail, and Qt
    # answers it by measuring an empty bounding box and warning on every
    # single draw that the mask is too big.
    for parent in root.iter():
        for child in list(parent):
            if child.tag == f"{{{SVG}}}g" and len(child) == 0 and not child.text:
                parent.remove(child)

    # And the masks nothing refers to any more.
    used = {element.get("mask") for element in root.iter()}
    for parent in root.iter():
        for child in list(parent):
            if child.tag == f"{{{SVG}}}mask" and f"url(#{child.get('id')})" not in used:
                parent.remove(child)

    # The pack asks for a 512-pixel drawing of a 128-unit icon, which is one
    # size baked into a thing whose point is having none.
    box = root.get("viewBox", "").split()
    if len(box) == 4:
        root.set("width", box[2])
        root.set("height", box[3])

    written = ElementTree.tostring(root, encoding="unicode")
    written = re.sub(r"\s+", " ", written).replace("> <", "><")
    return f"<!-- {NOTICE} -->\n{written}\n"


def render(svg: Path, png: Path, size: int) -> None:
    """One PNG, drawn by the same Qt that will draw the icon in the window.

    Not by a general-purpose rasteriser, and for the reason this script exists
    at all: the pack looked right in every renderer but the one that matters.
    An icon proved by Qt is an icon proved.
    """
    from PySide6.QtCore import QSize
    from PySide6.QtGui import QImageReader

    reader = QImageReader(str(svg))
    reader.setScaledSize(QSize(size, size))
    image = reader.read()
    if image.isNull():
        raise SystemExit(f"{svg}: Qt will not read it -- {reader.errorString()}")
    if not image.save(str(png)):
        raise SystemExit(f"{png}: could not be written")


def main() -> int:
    if not FONTS.exists():
        print("no fonts/ -- the wordmark cannot be drawn", file=sys.stderr)
        return 1

    written = []

    # The application icon, scalable and sized. KDE's naming: sc- for the
    # scalable one, a size prefix for the rest.
    scalable = HERE / f"sc-apps-{APP}.svg"
    scalable.write_text(correct(PACK / "fretwork-icon.svg"))
    written.append(scalable)

    symbolic = HERE / f"{APP}-symbolic.svg"
    symbolic.write_text(correct(PACK / "fretwork-icon-mono.svg"))
    written.append(symbolic)

    for size in PNG_SIZES:
        png = HERE / f"{size}-apps-{APP}.png"
        render(scalable, png, size)
        written.append(png)

    # The badges on the tracks rail, and the same badges in paper for the dark
    # panels: a disc that is ink on the page is invisible on the effects deck.
    for instrument in ("guitar", "bass", "drums", "keys"):
        for tone, suffix in (("", ""), ("-paper", "-paper")):
            out = HERE / f"instrument-{instrument}{suffix}.svg"
            out.write_text(correct(PACK / "instruments" / f"{instrument}{tone}.svg"))
            written.append(out)

    for path in written:
        print(path.relative_to(HERE.parent))
    return 0


if __name__ == "__main__":
    sys.exit(main())
